# Numpy

In [1]:
import numpy as np

In [4]:
a = [0,1,4,5]
arr=np.array(a)
type(arr)

numpy.ndarray

In [5]:
M= np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [6]:
M.shape

(2, 2)

In [7]:
np.shape(M)

(2, 2)

In [10]:
M[0,0]=0

In [11]:
M

array([[0, 2],
       [3, 4]])

In [16]:
M= np.array([[1,2],[3,4]], dtype=complex)
#complex, int64, int128, (floats)
M

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [18]:
a= np.arange(0,10,0.1)
a

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9])

In [20]:
b= np.linspace(0,10,25) #Inicio, fin, numero de puntos
b

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [28]:
np.logspace(0,10,11, base=np.e)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [22]:
x,y = np.mgrid[0:5, 0:5]

In [23]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [24]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [29]:
from numpy import random

In [50]:
M=random.rand(5,5)
M

array([[ 0.8633818 ,  0.77653694,  0.57331391,  0.09775322,  0.4553326 ],
       [ 0.61723332,  0.14477242,  0.6755276 ,  0.13681649,  0.39061789],
       [ 0.68581143,  0.29512684,  0.4697244 ,  0.52161484,  0.76857794],
       [ 0.7338374 ,  0.93332384,  0.72065233,  0.29430362,  0.8127644 ],
       [ 0.14367401,  0.0369242 ,  0.62806479,  0.66289303,  0.43475806]])

In [51]:
random.randn(5,5)

array([[-0.81689947, -0.38485926, -1.76715423,  0.65825495,  0.69263326],
       [ 0.25002723, -1.33563455,  0.68665677,  1.61140375, -0.63796204],
       [-0.36923286,  1.43869389,  1.45238551, -0.91091352, -0.8732798 ],
       [ 1.20542511,  0.89014864,  0.08084957, -0.58952651,  0.25031079],
       [-1.08103378, -0.20082709, -1.0530977 , -1.35098572, -0.71130474]])

In [32]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [35]:
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [37]:
d=np.zeros(5)
d

array([ 0.,  0.,  0.,  0.,  0.])

In [38]:
d=np.ones(3)
d

array([ 1.,  1.,  1.])

In [39]:
%%bash
echo '
1800 1 1 -6.1 -6.1 1
1800 1 2 -15.4 -15.4 1
' > test.dat

In [40]:
data=np.genfromtxt('test.dat')

In [41]:
data

array([[  1.80000000e+03,   1.00000000e+00,   1.00000000e+00,
         -6.10000000e+00,  -6.10000000e+00,   1.00000000e+00],
       [  1.80000000e+03,   1.00000000e+00,   2.00000000e+00,
         -1.54000000e+01,  -1.54000000e+01,   1.00000000e+00]])

In [42]:
data.shape

(2, 6)

In [45]:
data[1,:]

array([  1.80000000e+03,   1.00000000e+00,   2.00000000e+00,
        -1.54000000e+01,  -1.54000000e+01,   1.00000000e+00])

In [52]:
np.savetxt("random-matrix.csv", M)

In [53]:
!cat random-matrix.csv

8.633817964661938404e-01 7.765369444686607281e-01 5.733139116022523130e-01 9.775321523435231974e-02 4.553326005509699126e-01
6.172333200571292755e-01 1.447724164410572056e-01 6.755275955117490128e-01 1.368164892751687622e-01 3.906178877387653792e-01
6.858114281428889791e-01 2.951268440533025839e-01 4.697244044153378040e-01 5.216148399006363956e-01 7.685779433875490341e-01
7.338374027968845859e-01 9.333238370490453129e-01 7.206523300618746797e-01 2.943036159337293345e-01 8.127643960104076193e-01
1.436740144178170198e-01 3.692420415945441015e-02 6.280647878762466441e-01 6.628930274723277005e-01 4.347580570271607492e-01


In [54]:
np.savetxt("random-matrix.csv", M, fmt='%.5f')

In [55]:
!cat random-matrix.csv

0.86338 0.77654 0.57331 0.09775 0.45533
0.61723 0.14477 0.67553 0.13682 0.39062
0.68581 0.29513 0.46972 0.52161 0.76858
0.73384 0.93332 0.72065 0.29430 0.81276
0.14367 0.03692 0.62806 0.66289 0.43476


In [56]:
A= np.loadtxt("random-matrix.csv")
A

array([[ 0.86338,  0.77654,  0.57331,  0.09775,  0.45533],
       [ 0.61723,  0.14477,  0.67553,  0.13682,  0.39062],
       [ 0.68581,  0.29513,  0.46972,  0.52161,  0.76858],
       [ 0.73384,  0.93332,  0.72065,  0.2943 ,  0.81276],
       [ 0.14367,  0.03692,  0.62806,  0.66289,  0.43476]])

In [57]:
!gzip random-matrix.csv

In [59]:
B=np.loadtxt("random-matrix.csv.gz") #Lee tablas comprimidas!
B

array([[ 0.86338,  0.77654,  0.57331,  0.09775,  0.45533],
       [ 0.61723,  0.14477,  0.67553,  0.13682,  0.39062],
       [ 0.68581,  0.29513,  0.46972,  0.52161,  0.76858],
       [ 0.73384,  0.93332,  0.72065,  0.2943 ,  0.81276],
       [ 0.14367,  0.03692,  0.62806,  0.66289,  0.43476]])

In [61]:
np.savetxt("random-matrix.csv", M, fmt='%.5f', delimiter=',')

In [62]:
!cat random-matrix.csv

0.86338,0.77654,0.57331,0.09775,0.45533
0.61723,0.14477,0.67553,0.13682,0.39062
0.68581,0.29513,0.46972,0.52161,0.76858
0.73384,0.93332,0.72065,0.29430,0.81276
0.14367,0.03692,0.62806,0.66289,0.43476


In [63]:
np.save("random-matrix.npy", M) #Muy eficiente pero no estandar, ideal para achivos temporales

In [64]:
C= np.load("random-matrix.npy")

In [65]:
C

array([[ 0.8633818 ,  0.77653694,  0.57331391,  0.09775322,  0.4553326 ],
       [ 0.61723332,  0.14477242,  0.6755276 ,  0.13681649,  0.39061789],
       [ 0.68581143,  0.29512684,  0.4697244 ,  0.52161484,  0.76857794],
       [ 0.7338374 ,  0.93332384,  0.72065233,  0.29430362,  0.8127644 ],
       [ 0.14367401,  0.0369242 ,  0.62806479,  0.66289303,  0.43475806]])

In [66]:
M.ndim

2

In [67]:
M[2,1]

0.29512684405330258

In [68]:
M[1]

array([ 0.61723332,  0.14477242,  0.6755276 ,  0.13681649,  0.39061789])

In [69]:
M[0,:2]

array([ 0.8633818 ,  0.77653694])

In [71]:
M[0,0]=0
M

array([[ 0.        ,  0.77653694,  0.57331391,  0.09775322,  0.4553326 ],
       [ 0.61723332,  0.14477242,  0.6755276 ,  0.13681649,  0.39061789],
       [ 0.68581143,  0.29512684,  0.4697244 ,  0.52161484,  0.76857794],
       [ 0.7338374 ,  0.93332384,  0.72065233,  0.29430362,  0.8127644 ],
       [ 0.14367401,  0.0369242 ,  0.62806479,  0.66289303,  0.43475806]])

In [73]:
M[0,:]=0
M

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.61723332,  0.14477242,  0.6755276 ,  0.13681649,  0.39061789],
       [ 0.68581143,  0.29512684,  0.4697244 ,  0.52161484,  0.76857794],
       [ 0.7338374 ,  0.93332384,  0.72065233,  0.29430362,  0.8127644 ],
       [ 0.14367401,  0.0369242 ,  0.62806479,  0.66289303,  0.43475806]])