In [1]:
import numpy as np

A=np.array([[n+m*10 for n in range(5)] for m in range(5)])

In [2]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [3]:
A[1:4,1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])